### ISSUE TITLE
R3 version of the game will crash when installing GTFO-API

### ISSUE THREAD

**Issue by djkcyl** [Kasuromi/GTFO-API#47]
```
[Message: Preloader] BepInEx 6.0.0-be.665 - GTFO
[Message: Preloader] Built from commit 6aabdb5ff9500fca541dbd66df7fbd7fe1dacd78
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.21f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [GTFO-API 0.4.0]
[Info   :Il2CppInterop] Registered mono type GTFO.API.Impl.NetworkAPI_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Impl.AssetAPI_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Wrappers.ItemWrapped in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Utilities.Impl.ThreadDispatcher_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Utilities.Impl.CoroutineDispatcher_Impl in il2cpp domain
[Warning:  GTFO-API] [GTFO-API]: Syringes are currently disabled in this version
[Info   :   BepInEx] Loading [MTFO 4.4.4+git847ea25-main]
[Message:   BepInEx] Chainloader startup complete
[Warning:  GTFO-API] [AssetAPI]: Storing asset bundles in the config path is deprecated and will be removed in a future version of GTFO-API. The path has been moved to 'BepInEx\Assets\AssetBundles'.
```

**Comment by djkcyl** [comment]
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at UnityEngine.AssetBundle.LoadAsset_Internal(System.String, Il2CppSystem.Type)
   at UnityEngine.AssetBundle.LoadAsset(System.String, Il2CppSystem.Type)
   at UnityEngine.AssetBundle.LoadAsset(System.String)
   at GTFO.API.AssetAPI.RegisterAssetBundle(UnityEngine.AssetBundle)
   at GTFO.API.AssetAPI.LoadAndRegisterAssetBundle(System.String)
   at GTFO.API.AssetAPI.LoadAssetBundles(System.String, Boolean)
   at GTFO.API.AssetAPI.LoadAssetBundles()
   at GTFO.API.Impl.AssetAPI_Impl.Awake()
   at DynamicClass.Trampoline_VoidThisGTFO.API.Impl.AssetAPI_ImplAwake(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
   at DynamicClass.Invoker_VoidThis(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*, IntPtr, IntPtr*)
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
   at UnityEngine.GameObject.AddComponent[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at GTFO.API.Resources.APIStatus.CreateApi[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String)
   at GTFO.API.Patches.AssetShardManager_Patches.Setup_Postfix()
   at DynamicClass.DMD<AssetShards.AssetShardManager::Setup>(AssetShards.AssetShardManager)
   at DynamicClass.(il2cpp -> managed) Setup(il2cpp -> managed) Setup(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
```

**Comment by djkcyl** [comment]
```
[Message: Preloader] BepInEx 6.0.0-be.665 - GTFO
[Message: Preloader] Built from commit 6aabdb5ff9500fca541dbd66df7fbd7fe1dacd78
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.21f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Debug  :   BepInEx] Game executable path: E:\Program Files (x86)\Steam\steamapps\common\GTFO\GTFO.exe
[Debug  :   BepInEx] Interop assembly directory: C:\Users\djkcyl\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\Default\BepInEx\interop
[Debug  :   BepInEx] BepInEx root path: C:\Users\djkcyl\AppData\Roaming\r2modmanPlus-local\GTFO\profiles\Default\BepInEx
[Info   : Preloader] 0 patcher plugins loaded
[Debug  :AssemblyPatcher] Assembly loaded: Addons-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: AssetPrefabs-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Assets-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: BlendEnv.dll
[Debug  :AssemblyPatcher] Assembly loaded: BlendHS.dll
[Debug  :AssemblyPatcher] Assembly loaded: CellSound-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: CommandSystem.dll
[Debug  :AssemblyPatcher] Assembly loaded: DevConsoleCommands-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: DevConsoloe-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Dissonance-integrations-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: DissonanceVoip.dll
[Debug  :AssemblyPatcher] Assembly loaded: DropServerSDK-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: ExcludeInBuild-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: FluffyUnderware.DevTools.dll
[Debug  :AssemblyPatcher] Assembly loaded: FPSRenderer.dll
[Debug  :AssemblyPatcher] Assembly loaded: GameData-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: GlobalFramework-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: GUIX-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppMono.Security.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2Cppmscorlib.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Configuration.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Core.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Data.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Diagnostics.StackTrace.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Globalization.Extensions.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.IO.Compression.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Net.Http.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Numerics.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Runtime.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Runtime.Serialization.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Xml.dll
[Debug  :AssemblyPatcher] Assembly loaded: Il2CppSystem.Xml.Linq.dll
[Debug  :AssemblyPatcher] Assembly loaded: LibTessDotNet.dll
[Debug  :AssemblyPatcher] Assembly loaded: LogUtils.dll
[Debug  :AssemblyPatcher] Assembly loaded: Modules-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: NativeHeap.dll
[Debug  :AssemblyPatcher] Assembly loaded: netstandard.dll
[Debug  :AssemblyPatcher] Assembly loaded: Newtonsoft.Json.dll
[Debug  :AssemblyPatcher] Assembly loaded: Notification-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: PlayFab-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Plugins-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Prototype.dll
[Debug  :AssemblyPatcher] Assembly loaded: Prototypes_ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Resources-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: RootMotion-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Scenes-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Shards-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: SNet_ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: StandardAssets-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: SteamDataAttribution-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: SteamWorks_ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: ToolBuddy.Curvy.dll
[Debug  :AssemblyPatcher] Assembly loaded: ToolBuddy.Curvy.Examples.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Analytics.DataPrivacy.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Burst.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Burst.Unsafe.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Collections.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Mathematics.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.Postprocessing.Runtime.dll
[Debug  :AssemblyPatcher] Assembly loaded: Unity.TextMeshPro.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AccessibilityModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AIModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AndroidJNIModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AnimationModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ARModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AssetBundleModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.AudioModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ClothModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ClusterInputModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ClusterRendererModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.CoreModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.CrashReportingModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.DirectorModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.DSPGraphModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.GameCenterModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.GridModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.HotReloadModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ImageConversionModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.IMGUIModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.InputLegacyModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.InputModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.JSONSerializeModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.LocalizationModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ParticleSystemModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.PerformanceReportingModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.Physics2DModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.PhysicsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ProfilerModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.ScreenCaptureModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.SharedInternalsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.SpriteMaskModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.SpriteShapeModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.StreamingModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.SubstanceModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.SubsystemsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TerrainModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TerrainPhysicsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TextCoreModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TextRenderingModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TilemapModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.TLSModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UI.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UIElementsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UIModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UmbraModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UNETModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityAnalyticsModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityConnectModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityTestProtocolModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityWebRequestAssetBundleModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityWebRequestAudioModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityWebRequestModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityWebRequestTextureModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.UnityWebRequestWWWModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.VehiclesModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.VFXModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.VideoModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.VRModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.WindModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityEngine.XRModule.dll
[Debug  :AssemblyPatcher] Assembly loaded: UnityFileDebug-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Utils-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Windows-ASM.dll
[Debug  :AssemblyPatcher] Assembly loaded: Wwise-ASM.dll
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Debug  : Preloader] Runtime invoke pointer: 0x7FF8686B17C0
[Debug  :DobbyDetour] Preparing detour from 0x7FF8686B17C0 to 0x7FF82AFE3264
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF8286C0000
[Debug  :DobbyDetour] Original: 7FF8686B17C0, Trampoline: 7FF8286C0000, diff: 3FFF17C0
[Debug  : Preloader] Runtime invoke patched
[Debug  :Il2CppInterop] il2cpp_object_get_virtual_method: 0x7FF8686B16A0
[Debug  :Il2CppInterop] Object::GetVirtualMethod: 0x7FF8686EE670
[Debug  :Il2CppInterop] GenericMethod::GetMethod: 0x7FF86871AE90
[Debug  :DobbyDetour] Preparing detour from 0x7FF86871AE90 to 0x7FF82AFE32A4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF828720000
[Debug  :DobbyDetour] Original: 7FF86871AE90, Trampoline: 7FF828720000, diff: 3FFFAE90
[Debug  :Il2CppInterop] il2cpp_image_get_class: 0x7FF8686B1440
[Debug  :Il2CppInterop] Image::GetType: 0x7FF8686EC920
[Debug  :Il2CppInterop] MetadataCache::GetTypeInfoFromTypeDefinitionIndex: 0x7FF8686EC990
[Debug  :DobbyDetour] Preparing detour from 0x7FF8686EC990 to 0x7FF82AFE32E4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF828720020
[Debug  :DobbyDetour] Original: 7FF8686EC990, Trampoline: 7FF828720020, diff: 3FFCC970
[Debug  :Il2CppInterop] Class::GetDefaultFieldValue: 0x7FF8686E7030
[Debug  :DobbyDetour] Preparing detour from 0x7FF8686E7030 to 0x7FF82AFE3324
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF828720040
[Debug  :DobbyDetour] Original: 7FF8686E7030, Trampoline: 7FF828720040, diff: 3FFC6FF0
[Debug  :Il2CppInterop] Class::Init: 0x7FF8686EEE80
[Debug  :Il2CppInterop] il2cpp_class_from_il2cpp_type: 0x7FF8686B0D00
[Debug  :Il2CppInterop] Class::FromIl2CppType: 0x7FF8686E2680
[Debug  :DobbyDetour] Preparing detour from 0x7FF8686E2680 to 0x7FF82AFE3364
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF828720060
[Debug  :DobbyDetour] Original: 7FF8686E2680, Trampoline: 7FF828720060, diff: 3FFC2620
[Debug  :Il2CppInterop] il2cpp_class_from_name: 0x7FF8686B0D10
[Debug  :Il2CppInterop] Class::FromName: 0x7FF8686E28A0
[Debug  :DobbyDetour] Preparing detour from 0x7FF8686E28A0 to 0x7FF82AFE33A4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF828720080
[Debug  :DobbyDetour] Original: 7FF8686E28A0, Trampoline: 7FF828720080, diff: 3FFC2820
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Debug  :     Unity] Test call after applying unity logging hook
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [GTFO-API 0.4.0]
[Info   :Il2CppInterop] Registered mono type GTFO.API.Impl.NetworkAPI_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Impl.AssetAPI_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Wrappers.ItemWrapped in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Utilities.Impl.ThreadDispatcher_Impl in il2cpp domain
[Info   :Il2CppInterop] Registered mono type GTFO.API.Utilities.Impl.CoroutineDispatcher_Impl in il2cpp domain
[Debug  :DobbyDetour] Preparing detour from 0x7FF86A7DCD20 to 0x7FF82BE701E4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0000
[Debug  :DobbyDetour] Original: 7FF86A7DCD20, Trampoline: 7FF82A7E0000, diff: 3FFFCD20
[Debug  :DobbyDetour] Preparing detour from 0x7FF8688ADCB0 to 0x7FF82BE70224
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0020
[Debug  :DobbyDetour] Original: 7FF8688ADCB0, Trampoline: 7FF82A7E0020, diff: 3E0CDC90
[Debug  :DobbyDetour] Preparing detour from 0x7FF8688AD6C0 to 0x7FF82BE70264
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0040
[Debug  :DobbyDetour] Original: 7FF8688AD6C0, Trampoline: 7FF82A7E0040, diff: 3E0CD680
[Debug  :DobbyDetour] Preparing detour from 0x7FF868E28A20 to 0x7FF82BE702A4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0060
[Debug  :DobbyDetour] Original: 7FF868E28A20, Trampoline: 7FF82A7E0060, diff: 3E6489C0
[Debug  :DobbyDetour] Preparing detour from 0x7FF868771AC0 to 0x7FF82BE702E4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0080
[Debug  :DobbyDetour] Original: 7FF868771AC0, Trampoline: 7FF82A7E0080, diff: 3DF91A40
[Debug  :DobbyDetour] Preparing detour from 0x7FF868933940 to 0x7FF82BE70324
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E00A0
[Debug  :DobbyDetour] Original: 7FF868933940, Trampoline: 7FF82A7E00A0, diff: 3E1538A0
[Debug  :DobbyDetour] Preparing detour from 0x7FF868DBD7D0 to 0x7FF82BE70364
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E00C0
[Debug  :DobbyDetour] Original: 7FF868DBD7D0, Trampoline: 7FF82A7E00C0, diff: 3E5DD710
[Debug  :DobbyDetour] Preparing detour from 0x7FF8693073C0 to 0x7FF82BE703A4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E00E0
[Debug  :DobbyDetour] Original: 7FF8693073C0, Trampoline: 7FF82A7E00E0, diff: 3EB272E0
[Warning:  GTFO-API] [GTFO-API]: Syringes are currently disabled in this version
[Message:   BepInEx] Chainloader startup complete
[Debug  : Preloader] Runtime invoke unpatched
[Message:     Unity] WwiseUnity: Initialize sound engine... basePath: GeneratedSoundBanks
[Message:     Unity] Wwise defaultPoolSize: 16777216 AkSoundEngine.AK_SOUNDBANK_VERSION: 125
[Message:     Unity] WwiseUnity: Sound engine initialized.
[Message:     Unity] InControl (version 1.6.17 build 9143)
[Message:     Unity] <size=13><color=red>TODO : Implement m_badPacketQuestion/m_badPacketAnswer and the SNet_BadPacketCatcher</color></size>
[Message:     Unity] > GLOBAL SetupManagers, State : Dev HasNetwork: True
[Message:     Unity] GameDataInit.Initialize
[Message:     Unity] ------------------------------------------------------------  MusicManager. Loading soundbank for music! ------------------------------------------------------------
[Debug  :DobbyDetour] Preparing detour from 0x7FF868D88C90 to 0x7FF82BE704A4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0100
[Debug  :DobbyDetour] Original: 7FF868D88C90, Trampoline: 7FF82A7E0100, diff: 3E5A8B90
[Debug  :DobbyDetour] Preparing detour from 0x7FF86950C760 to 0x7FF82BE704E4
[Debug  :DobbyDetour] Prepared detour; Trampoline: 0x7FF82A7E0120
[Debug  :DobbyDetour] Original: 7FF86950C760, Trampoline: 7FF82A7E0120, diff: 3ED2C640
[Warning:     Unity] The referenced script on this Behaviour (Game Object '<null>') is missing!
[Message:     Unity] Setting watermark revision to 32545
[Warning:  GTFO-API] [AssetAPI]: Storing asset bundles in the config path is deprecated and will be removed in a future version of GTFO-API. The path has been moved to 'BepInEx\Assets\AssetBundles'.
```

**Comment by Kasuromi** [comment]
This isn't an issue with GTFO-API. One of the asset packs you are using hasn't updated their asset bundles to work with the new game version. The owner of the asset pack has to rerun `AssetBundleCompressor` on the new game files.
